### ISSUE TITLE
Pattern match by reference?

### ISSUE THREAD

**Issue by unleashy** [pbackus/sumtype#1]
Hey, I'm trying to alter a value inside a sumtype, but it doesn't seem to support pattern matching by reference:
```d
alias Value = SumType!(long, double);
auto value = Value(3.14);
value.match!(
    (long) {},
    (ref double d) { d *= 2; } // compile-time error right here
);
```
The error says, `Error: static assert:  "No matching handler for type double"`. Is there a workaround (I couldn't find a way to extract the value inside, even though I know what the type is)?

**Comment by pbackus** [comment]
Thanks for reporting. I've pushed a fix for this and tagged it as `v0.4.1`. Please update and verify that it works for you.

**Comment by unleashy** [comment]
It works! Thanks for the fast response! Also, I think you forgot to push the v0.4.1 tag, as I can't see it anywhere in github. Thanks anyways!
